# Generated by Django 3.1.5 on 2021-01-25 18:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_house_poly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('data_in', models.DateField(blank=True, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
                ('id_style1', models.IntegerField(blank=True, null=True)),
                ('build_area', models.FloatField(blank=True, null=True)),
                ('use_area', models.FloatField(blank=True, null=True)),
                ('number_apa', models.FloatField(blank=True, null=True)),
                ('population', models.FloatField(blank=True, null=True)),
                ('seats', models.FloatField(blank=True, null=True)),
                ('seats_cars', models.FloatField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_le_1', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857)),
            ],
            options={
                'db_table': 'buildings_project',
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('stationnam', models.CharField(blank=True, max_length=100, null=True)),
                ('platformx', models.CharField(blank=True, max_length=100, null=True)),
                ('platformy', models.CharField(blank=True, max_length=100, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857)),
            ],
            options={
                'db_table': 'bus_stops_project1',
            },
        ),
        migrations.CreateModel(
            name='RedLine',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('id_style', models.CharField(blank=True, max_length=100, null=True)),
                ('id_style1', models.IntegerField(blank=True, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_le_1', models.FloatField(blank=True, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=3857)),
            ],
            options={
                'db_table': 'red_lines_project',
            },
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
